# Generated by Django 2.0.5 on 2018-10-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=3)),
                ('priority', models.CharField(choices=[('EM', 'Emergency'), ('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='ME', max_length=2)),
                ('dead_line', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
