# Generated by Django 2.0.5 on 2018-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_done',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('4', 'Emergency'), ('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=1),
        ),
    ]
